### ISSUE TITLE
Allow Schema Definition with Fixed Byte Sizes for Strings and Other Data Types

### ISSUE THREAD

**Issue by nnajiabraham** [iwoplaza/typed-binary#32]
I came across this package from a tweet recently and started using it for a project to learn more about buffers, bytes, etc., in NodeJS. If this feature is possible to implement, I'd love to contribute with some guidance, as I'm still a beginner. 🙏

Would it be possible to define the byte size of a value when creating a schema? For example, the current documentation states that bin.string is a variable-length string of ASCII characters. Here's an example of the current approach:

```
export const PlayerUpdatePacket = bin.object({
  id: bin.string, // string is a variable-length string of ASCII characters.
  x: bin.f32,
  y: bin.f32,
});

const packet = {
  id: 0,
  x: 2.4,
  y: 1.6,
} as const;

const packetSize = PlayerUpdatePacket.measure(packet).size;
const buffer = Buffer.alloc(packetSize);
```

It would be great if we could specify the allocated byte size for the id in the PlayerUpdatePacket. For instance, the schema could be defined as follows:

```
export const PlayerUpdatePacket = bin.object({
  id: bin.string(20), // where 20 is the fixed byte size for the string
  x: bin.f32,
  y: bin.f32,
});
```

I used bin.string as an example, but would this also be possible for other types, like integers, floats, or even generic types?

This feature could also enable an API to get the total byte size for the values in an object. This could be used directly in the Buffer.alloc call. In the case of the example above, it might look like this:

```
export const PlayerUpdatePacket = bin.object({
  id: bin.string(10), // where 10 is the fixed byte size for the string
  x: bin.float(32), // 32-bit float
  y: bin.float(32), // 32-bit float
});

console.log(PlayerUpdatePacket.size); // 74 bytes total
const buffer = Buffer.alloc(PlayerUpdatePacket.size);
```

Would love to know your thoughts on whether this feature could be implemented!

**Comment by iwoplaza** [comment]
Thank you for creating the issue!

The `bin.chars` should help you encode a string of known size, there you can pass the length in bytes by calling `bin.chars(20)` as an example. By doing this, `Buffer.alloc(PlayerUpdatePacket.maxSize)` should allocate the appropriate buffer for any value of `PlayerUpdatePacket` 🙌 .

The `.size` API you're envisioning already exists, but is kind of hidden and undocumented 🙈. It's the `.maxSize` property on some schemas. It returns the number of bytes needed to encode any value the schema describes. In the case of a variable-length schema, that value is `NaN`, since we cannot compute an upper bound. By using `bin.chars` though, the schema's max size is known.

Doing the same for floats would be a bit tricker, as there are many different ways to encode a float into an n-number of bytes. I do plan on adding `f16` as a primitive though, could be useful 💜.

Hopefully that clears things up a bit, let me know if you want to discuss anything further!

**Comment by nnajiabraham** [comment]
@iwoplaza Thanks so much! Using `bin.chars(20)` and `.maxSize` works. I can see how doing the same for floats or ints can be tricky...

Is there an API for validating/ensuring that the size of the char is not violated when assigning values to the schema? 

For example: 

```
export const PlayerUpdatePacket = bin.object({
  id: bin.chars(2), 
  x: bin.f32,
  y: bin.f32,
});

PlayerUpdatePacket.write(writer, {
  id: 'abc' // this should trigger an error maybe since byte size of abc is 3
  ...
}
```

My little/naive understanding tells me this might be tricky or impossible but figured I could ask

**Comment by iwoplaza** [comment]
The code you wrote should raise an error, and if it doesn't, adding such a guard should not be a problem 😃. You can try and run this code locally on your machine and see if it indeed throws an error.

**Comment by iwoplaza** [comment]
I wrote a StackBlitz to showcase this behavior. Hope you find it useful 🙌
https://stackblitz.com/edit/vitejs-vite-cps536?file=src%2Fmain.ts

**Comment by nnajiabraham** [comment]
OMG! You're a wizard. I am honestly enjoying this lib, thank you so much 👏 @iwoplaza 
How can I help with updating the docs for the `.maxSize` and any other properties needed

**Comment by iwoplaza** [comment]
You should be able to fork the repository, and then create a Pull Request with any changes you made to your fork. Then if everything is okay, it will be merged 💜
